
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env.local.example
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx next start -p 80
